### ISSUE TITLE
Example of multi-depth inheritence

### ISSUE THREAD

**Issue by jadrake75** [Rettend/pinia-generic#1]
So I have successfully used pinia-generic in my project to extend a base store.  An example would be for the generic:
https://github.com/stamp-web/stamp-web-vuejs/blob/main/src/stores/baseModelStore.ts

and then the implementaton:
https://github.com/stamp-web/stamp-web-vuejs/blob/main/src/stores/albumStore.ts

This works Perfectly! and compared to my first attempt of a single store having entity type named methods is a thing of beauty.   But I have been having trouble figuring out how to declare a level in between.  ie. a Generic Store to extend a Generic Store.  Ideally I'd want something like

```
baseModelStore<T extends PersistedModel> { }
baseManagedStore<T extends PersistedNamedModel>{ // extends the baseModelStore but has some new implementation }
albumStore extends baseManagedStore<Album>
```

For the `baseManagedStore` I created my type that extended the `BaseModelStoreType` but then it was unclear whether for the store I have to make this "useStore" or use the "defineGenericStore".  The later seems like what I'd want here - to define a generic, add some implementation but extend the `baseModelStore`  - just not sure how to make it "extend" the `baseModelStore` I guess.

**Comment by Rettend** [comment]
Hello! Awesome that you tried this package.

I did not try extending base stores with base stores at all, but this is clearly a feature this package should have, so I experimented a bit [here](https://github.com/Rettend/pinia-generic/blob/742e6cfffdfa00457e8dc7430bf645ee3b4aca54/playground/src/store.ts#L156C5-L156C5).
However, I wasn't able to create anything that's working 😕 and I also didn't want to leave you hanging.

Definitely the `defineGenericStore` should be used for this and that is what I tried modifying.
(I currently have no idea why the [`defineGenericStore` function](https://github.com/Rettend/pinia-generic/blob/742e6cfffdfa00457e8dc7430bf645ee3b4aca54/src/generic.ts#L60) on the new branch does not work)

So I will look back into this more.

I've also planned to revisit this project and release 1.0 as I want to reduce the ceremony this package has by a lot, and I will include multi-level inheritance.

**Comment by jadrake75** [comment]
Glad to know it wasn't something in my TS knowledge that was preventing me from getting this to work.  I appreciate the interest and I do like the direction this project is going.

**Comment by Rettend** [comment]
@jadrake75 I fixed it and now generic stores can be extended by generic stores!

There might be issues so I published a pre-release, which you can try like this:

```
npm i pinia-generic@0.2.0-beta.0
```

You can find full examples here:
- [tests](https://github.com/Rettend/pinia-generic/blob/test-multi-level-inherit/test/generic.test.ts#L118-L225)
- [more realistic example](https://github.com/Rettend/pinia-generic/blob/test-multi-level-inherit/playground/src/store.ts#L156-L258)

Basically the `defineGenericStore` function can now take a generic store as the last parameter (just like the generic `PiniaStore` type before), and it copies all its properties to the new generic store.

So if we have a generic store here: 

```ts
interface BaseItem {
  id: number
}

type BaseStore1<T extends BaseItem> = PiniaStore<
  'base1',
  {
    value1: T | null
  }
>

function baseStore1<T extends BaseItem>() {
  return defineGenericStore<BaseStore1<T>>({
    state: {
      value1: null,
    },
  })
}
```

extending `baseStore1` by `baseStore2` means that we put `baseStore1` in `baseStore2`'s type:
```ts
type BaseStore2<T extends BaseItem> = PiniaStore<
  'base2',
  {
    value2: T | null
  },
  {},
  {},
  BaseStore1<T> // Note this line
>
```
and function:

```ts
function baseStore2<T extends BaseItem>() {
  return defineGenericStore<BaseStore2<T>, BaseStore1<T>>({
    state: {
      value2: null,
    },
  },
  baseStore1<T>(), // Note this line
  )
}
```

> [!IMPORTANT]
> The generic parameters still need to be explicitly supplied, and it's easy to mess up their order:
> ```ts
> return defineGenericStore<BaseStore2<T>, BaseStore1<T>>({ ... })
> ```
> A good way to think about it is that the first is the **store I am currently defining**, and the second is the **store whose properties it will inherit**

Both generic stores can be extended by regular stores further using `useStore()`.

Also note that if you want a store to extend multiple stores, that can only be done by creating an intermediate store, and extending that.

I will test this more and include it in the docs, then release v0.2.0.
Let me know if you find any issues 👍

**Comment by jadrake75** [comment]
@Rettend - apologize for not checking in on this.  I really appreciate this update and I pulled 0.2.0 into my project.  I was able to leverage it successfully and this simplified/removed a bunch of redundant code which I had for most of the services (but not all) due to a generic conflict.  Now I  can have

- BaseModelStore
   - BaseNamedModelStore
      - CountryStore
      - AlbumStore
      - CatalogueStore
      - SellerStore
   - StampStore
   - PreferenceStore

**NOTE** The following observation I am seeing on 0.2.0 but looking at your types.ts I do see it export the StoreThis symbol (so this might be an environment issue for me)

The only issue I am seeing, is defining any of the stores that extend a parent store, the IDE (I use Webstorm) is inferring the type as StoreThis<parentStore<T>> but I don't think this symbol is exported.  

![image](https://github.com/Rettend/pinia-generic/assets/3221886/8e73cc10-9d44-4cdc-95fd-53589967a850)


I was able to work around it by setting the return type explicitly to : any  but this should probably be cleaned up for better use in IDEs.

```
export function baseNamedModelStore<T extends PersistedNamedModel>() : any {
   return defineGenericStore<BaseNamedModelStore<T>, BaseModelStore<T>>( )
...
}

**Comment by Rettend** [comment]
@jadrake75  hey awesome to hear that!

Regarding the IDE issue I don't have it in vscode and I don't know how webstorm works.
If it helps, I exported the types, and you can test it like this if you use npm:

```cmd
npm i github:Rettend/pinia-generic#dist
``` 

Let me know if it solves it and I'll publish it to npm!

**Comment by jadrake75** [comment]
@Rettend yeah that cleaned it up.

**Comment by Rettend** [comment]
hm I can't seem to publish npm packages right now.... npm is broken
